language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_script:
- npm install grunt-cli -g
deploy:
  provider: heroku
  api_key:
    secure: UczDxM2jNrnfV4f6ALNhAOu498eLH6Mcg8zHFcq8XJ3EOCK0SXJKlVfHfZ1nQCBnKN0LBPc40sdqo7IEKIZt3hwKcBtwAnYKRbFuyvmXdyDkzsiNjEyA6mLldRr9AbUX5w4VqL/btFvvvgV1+5aPH3MtjUt5ZouMCp9SB9WOn5eVnWaSjem+QZ66Kjzungd1A9E3M5wYm2Lqb4Tta68p6IWuEFLr2BqHmWAI5Xf9Ix2fxU5J5GijQDVICjWPz1X3CZFcratIObyuf5awtqUigC1HNz95zt7PILM6SipnVtTIxqYnKju+qlfk1mCsyCE0U6yh/qB83p5MBpe81V1leTEtq0AhnIchiHgFdzcMhzUqwpS9is5MPbJK3ZtvswII5Jm9nwDIILDmjDDslcqjt8wn6JeVdvUYVRples0OFFARGcSvE75Y9yCTJ+mIhp6yvDQX6ky1waMH+ICRCFWG2o3HPwSjiXcqiZXKvNdZ8cpHe+vPSfOPZrqflyu1oLKRdJ+bbqvjSttPVd4mC1/16VrBbu6iqL4bhclEe1Y7/YnrsPn4pyUeGrq2c0hXL9tCt4WC4yBozPSmT+9nfrpSmdsqzOUBNnfPMO/Gx4RRdZQcvCZewnRtGL3gCSLiBgUh6t3Vtk3oE5qfLTCIw6EFTFrUOoMvJ7oKgfZN0JE9k90=
  app: mysterious-badlands-72714
  on:
    repo: rlynn523/shelter-dogs
